/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_tutorial_AddPerson */

#ifndef _Included_com_example_tutorial_AddPerson
#define _Included_com_example_tutorial_AddPerson
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_tutorial_AddPerson
 * Method:    print_addressbook_in_cpp
 * Signature: (Lcom/example/tutorial/AddressBookProtos/AddressBook;)V
 */
JNIEXPORT void JNICALL Java_com_example_tutorial_AddPerson_print_1addressbook_1in_1cpp
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
